name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test who3
      id: test-who3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test who3
        setup-command: rm -rf test; git clone https://github.com/KNU-ELEC462/lab1.git
          test; rm -rf who3_ref* test_*; cp test/* .; chmod +x *.sh
        command: "./test_who3.sh"
        timeout: 10
        max-score: 2
    - name: test who4
      id: test-who4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test who4
        setup-command: rm -rf test; git clone https://github.com/KNU-ELEC462/lab1.git
          test; rm -rf who3_ref* test_*; cp test/* .; chmod +x *.sh
        command: "./test_who4.sh"
        timeout: 10
        max-score: 4
    - name: test cp2
      id: test-cp2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test cp2
        setup-command: rm -rf test; git clone https://github.com/KNU-ELEC462/lab1.git
          test; rm -rf who3_ref* test_*; cp test/* .; chmod +x *.sh
        command: "./test_cp2.sh"
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-WHO3_RESULTS: "${{steps.test-who3.outputs.result}}"
        TEST-WHO4_RESULTS: "${{steps.test-who4.outputs.result}}"
        TEST-CP2_RESULTS: "${{steps.test-cp2.outputs.result}}"
      with:
        runners: test-who3,test-who4,test-cp2
